# yaml-language-server: $schema=https://raw.githubusercontent.com/golangci/golangci-lint/refs/tags/v2.10.1/jsonschema/golangci.jsonschema.json
version: "2"
output:
  formats:
    text:
      colors: true
linters:
  enable:
  - unconvert
  - gosec
  - errorlint
  - unparam
  - whitespace
  - wrapcheck
  - prealloc
  - nolintlint
