package attributes

// Key attribute key type
type Key string

const (
	// AttributeBackground xdot format string specifying an arbitrary background
	//
	// Valid for: Graphs.
	AttributeBackground Key = "_background"
	// AttributeArea indicates the preferred area for a node or empty cluster when
	// laid out by patchwork
	//
	// Valid for: Clusters, Nodes. Note: patchwork only
	AttributeArea Key = "area"
	// AttributeArrowHead style of arrowhead on the head node of an edge. This
	// will only appear if the dir attribute is forward or both
	//
	// Valid for: Edges.
	AttributeArrowHead Key = "arrowhead"
	// AttributeArrowSize multiplicative scale factor for arrowheads
	//
	// Valid for: Edges.
	AttributeArrowSize Key = "arrowsize"
	// AttributeArrowTail style of arrowhead on the tail node of an edge.
	// This will only appear if the dir attribute is back or both.
	//
	// Valid for: Edges.
	AttributeArrowTail Key = "arrowtail"
	// AttributeBb bounding box of drawing in points
	//
	// Valid for: Graphs. Note: write only
	AttributeBb Key = "bb"
	// AttributeBgcolor When attached to the root graph, this color is used as the
	// background for entire canvas.
	//
	// When a cluster attribute, it is used as the initial background for the
	// cluster. If a cluster has a filled style, the cluster’s fillcolor will
	// overlay the background color.
	//
	// If the value is a colorList, a gradient fill is used. By default, this is a
	// linear fill; setting style=radial will cause a radial fill. Only two colors
	// are used. If the second color (after a colon) is missing, the default color
	// is used for it. See also the gradientangle attribute for setting the
	// gradient angle.
	AttributeBgcolor            Key = "bgcolor"
	AttributeCenter             Key = "center"
	AttributeCharset            Key = "charset"
	AttributeClass              Key = "class"
	AttributeClusterRank        Key = "clusterrank"
	AttributeColor              Key = "color"
	AttributeColorScheme        Key = "colorscheme"
	AttributeComment            Key = "comment"
	AttributeCompound           Key = "compound"
	AttributeConcentrate        Key = "concentrate"
	AttributeConstraint         Key = "constraint"
	AttributeDamping            Key = "Damping"
	AttributeDecorate           Key = "decorate"
	AttributeDefaultDist        Key = "defaultdist"
	AttributeDim                Key = "dim"
	AttributeDimen              Key = "dimen"
	AttributeDir                Key = "dir"
	AttributeDirEdgeConstraints Key = "diredgeconstraints"
	AttributeDistortion         Key = "distortion"
	AttributeDpi                Key = "dpi"
	AttributeEdgeHref           Key = "edgehref"
	AttributeEdgeTarget         Key = "edgetarget"
	AttributeEdgeTooltip        Key = "edgetooltip"
	AttributeEdgeURL            Key = "edgeURL"
	AttributeEpsilon            Key = "epsilon"
	AttributeEsep               Key = "esep"
	AttributeFillColor          Key = "fillcolor"
	AttributeFixedSize          Key = "fixedsize"
	AttributeFontColor          Key = "fontcolor"
	AttributeFontName           Key = "fontname"
	AttributeFontNames          Key = "fontnames"
	AttributeFontPath           Key = "fontpath"
	AttributeFontSize           Key = "fontsize"
	AttributeForceLabels        Key = "forcelabels"
	AttributeGradientAngle      Key = "gradientangle"
	AttributeGroup              Key = "group"
	AttributeHeadLp             Key = "head_lp"
	AttributeHeadClip           Key = "headclip"
	AttributeHeadHref           Key = "headhref"
	AttributeHeadLabel          Key = "headlabel"
	AttributeHeadPort           Key = "headport"
	AttributeHeadTarget         Key = "headtarget"
	AttributeHeadTooltip        Key = "headtooltip"
	AttributeHeadURL            Key = "headURL"
	AttributeHeight             Key = "height"
	AttributeHref               Key = "href"
	AttributeID                 Key = "id"
	AttributeImage              Key = "image"
	AttributeImagePath          Key = "imagepath"
	AttributeImagePos           Key = "imagepos"
	AttributeImageScale         Key = "imagescale"
	AttributeInputScale         Key = "inputscale"
	AttributeK                  Key = "K"
	AttributeLabel              Key = "label"
	AttributeLabelScheme        Key = "label_scheme"
	AttributeLabelAngle         Key = "labelangle"
	AttributeLabelDistance      Key = "labeldistance"
	AttributeLabelFloat         Key = "labelfloat"
	AttributeLabelFontColor     Key = "labelfontcolor"
	AttributeLabelFontName      Key = "labelfontname"
	AttributeLabelFontSize      Key = "labelfontsize"
	AttributeLabelHref          Key = "labelhref"
	AttributeLabelJust          Key = "labeljust"
	AttributeLabelLoc           Key = "labelloc"
	AttributeLabelTarget        Key = "labeltarget"
	AttributeLabelTooltip       Key = "labeltooltip"
	AttributeLabelURL           Key = "labelURL"
	AttributeLandscape          Key = "landscape"
	AttributeLayer              Key = "layer"
	AttributeLayerListSep       Key = "layerlistsep"
	AttributeLayers             Key = "layers"
	AttributeLayerSelect        Key = "layerselect"
	AttributeLayerSep           Key = "layersep"
	AttributeLayout             Key = "layout"
	AttributeLen                Key = "len"
	AttributeLevels             Key = "levels"
	AttributeLevelsGap          Key = "levelsgap"
	AttributeLHead              Key = "lhead"
	AttributeLHeight            Key = "lheight"
	AttributeLp                 Key = "lp"
	AttributeLTail              Key = "ltail"
	AttributeLWidth             Key = "lwidth"
	AttributeMargin             Key = "margin"
	AttributeMaxIter            Key = "maxiter"
	AttributeMcLimit            Key = "mclimit"
	AttributeMinDist            Key = "mindist"
	AttributeMinLen             Key = "minlen"
	AttributeMode               Key = "mode"
	AttributeModel              Key = "model"
	AttributeMosek              Key = "mosek"
	AttributeNewRank            Key = "newrank"
	AttributeNodeSep            Key = "nodesep"
	AttributeNoJustify          Key = "nojustify"
	AttributeNormalize          Key = "normalize"
	AttributeNoTranslate        Key = "notranslate"
	AttributeNsLimit            Key = "nslimit"
	AttributeNsLimit1           Key = "nslimit1"
	AttributeOrdering           Key = "ordering"
	AttributeOrientation        Key = "orientation"
	AttributeOutputOrder        Key = "outputorder"
	AttributeOverlap            Key = "overlap"
	AttributeOverlapScaling     Key = "overlap_scaling"
	AttributeOverlapShrink      Key = "overlap_shrink"
	AttributePack               Key = "pack"
	AttributePackMode           Key = "packmode"
	AttributePad                Key = "pad"
	AttributePage               Key = "page"
	AttributePageDir            Key = "pagedir"
	AttributePenColor           Key = "pencolor"
	AttributePenWidth           Key = "penwidth"
	AttributePeripheries        Key = "peripheries"
	AttributePin                Key = "pin"
	AttributePos                Key = "pos"
	AttributeQuadTree           Key = "quadtree"
	AttributeQuantum            Key = "quantum"
	AttributeRank               Key = "rank"
	AttributeRankDir            Key = "rankdir"
	AttributeRankSep            Key = "ranksep"
	AttributeRatio              Key = "ratio"
	AttributeRects              Key = "rects"
	AttributeRegular            Key = "regular"
	AttributeRemincross         Key = "remincross"
	AttributeRepulsiveforce     Key = "repulsiveforce"
	AttributeResolution         Key = "resolution"
	AttributeRoot               Key = "root"
	AttributeRotate             Key = "rotate"
	AttributeRotation           Key = "rotation"
	AttributeSameHead           Key = "samehead"
	AttributeSameTail           Key = "sametail"
	AttributeSamplePoints       Key = "samplepoints"
	AttributeScale              Key = "scale"
	AttributeSearchSize         Key = "searchsize"
	AttributeSep                Key = "sep"
	AttributeShape              Key = "shape"
	AttributeShapeFile          Key = "shapefile"
	AttributeShowBoxes          Key = "showboxes"
	AttributeSides              Key = "sides"
	AttributeSize               Key = "size"
	AttributeSkew               Key = "skew"
	AttributeSmoothing          Key = "smoothing"
	AttributeSortv              Key = "sortv"
	AttributeSplines            Key = "splines"
	AttributeStart              Key = "start"
	AttributeStyle              Key = "style"
	AttributeStylesheet         Key = "stylesheet"
	AttributeTailLp             Key = "tail_lp"
	AttributeTailClip           Key = "tailclip"
	AttributeTailHref           Key = "tailhref"
	AttributeTailLabel          Key = "taillabel"
	AttributeTailPort           Key = "tailport"
	AttributeTailTarget         Key = "tailtarget"
	AttributeTailTooltip        Key = "tailtooltip"
	AttributeTailURL            Key = "tailURL"
	AttributeTarget             Key = "target"
	AttributeTooltip            Key = "tooltip"
	AttributeTrueColor          Key = "truecolor"
	AttributeURL                Key = "URL"
	AttributeVertices           Key = "vertices"
	AttributeViewport           Key = "viewport"
	AttributeVoroMargin         Key = "voro_margin"
	AttributeWeight             Key = "weight"
	AttributeWidth              Key = "width"
	AttributeXdotVersion        Key = "xdotversion"
	AttributeXlabel             Key = "xlabel"
	AttributeXlp                Key = "xlp"
	AttributeZ                  Key = "z"
)
